name: koentjoro
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile.prod
    networks:
      - frontend
      - shared_proxy_network
    # Ports removed - accessed via reverse proxy
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  frontend_node_modules:

networks:
  backend:
  frontend:
  shared_proxy_network:
    external: true
